version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
      POSTGRES_DB: app_db
    ports:
      - "54321:5432"
    volumes:
      - db_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_pg_data:
